description: Development tools and CLI utilities
packages:
  # Version control
  - git
  - github-cli
  - lazygit

  # Network utilities
  - curl
  - wget
  - openbsd-netcat
  - inetutils

  # File utilities
  - unzip
  - tree
  - ncdu

  # Clipboard (Wayland)
  - wl-clipboard

  # Build essentials
  - base-devel
  - clang
  - cmake
  - gdb
  - lldb
  - bear
  - ccache
  - mold

  # Zig
  - zig-master-bin
  - zls-master-bin

  # Debugging & Profiling
  - valgrind
  - strace

  # Shell/Script tools
  - shellcheck

  # Benchmarking
  - hyperfine

  # YAML processing
  - go-yq

  # Web/Scripting runtimes
  - nodejs
  - npm
  - python
  - python-pip

  # Search utilities
  - fzf
  - ripgrep
  - fd

  # System monitoring
  - htop
  - fastfetch

  # Lua formatting (for Neovim config)
  - stylua

  # AI coding assistant
  - opencode

  # Documentation
  - tldr

  # IDE
  - helix
