description: Development tools and CLI utilities
packages:
  - git
  - github-cli
  - curl
  - unzip
  - xclip
  - wl-clipboard
  - ncdu

  - base-devel
  - clang
  - cmake
  - gdb
  - lldb
  - bear
  - ccache
  - mold

  - go-yq

  - nodejs
  - npm
  - python
  - python-pip

  - fzf
  - ripgrep
  - fd

  - tree
  - wget
  - htop
  - fastfetch
  - openbsd-netcat
  - inetutils
  - lazygit
  - stylua

  - opencode
