description: Base system packages
packages:
  - base
  - base-devel
  - linux
  - linux-firmware
  - linux-headers
  - networkmanager
  - man-db
  - man-pages
  - sudo
  - openssh
  - pacman-contrib
  - zram-generator
  - flatpak
  - grub
  - efibootmgr
  - dmidecode
  - paru-bin
  
  # Required by scripts
  - bc
